name: Quotes
favicon: null
layout_spectrum: 0.5557
typography_spectrum: 0.7621708891820163
title: Web Design and Web Hosting by Quotes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#025a68'
    - '#027c8b'
    - '#00bdbe'
    - '#063644'
    - '#8feaf2'
  brandStrength: 0.4375
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
